//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugY_Configurator.Resources.Translation {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlugY_Configurator.Resources.Translation.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PLAYERS=&quot;players set to&quot;;
        ///
        ///SAVE=&quot;/save&quot;;
        ///SELECT_PAGE=&quot;/page&quot;;
        ///
        ///LOCK_MOUSE = &quot;/lockmouse&quot;;
        ///LOCK_MOUSE2 = &quot;/lock&quot;;
        ///UNLOCK_MOUSE = &quot;/unlockmouse&quot;;
        ///UNLOCK_MOUSE2 = &quot;/unlock&quot;;
        ///
        ///RENAME_CHAR=&quot;/renamechar&quot;;
        ///
        ///REPAGE_NAME = &quot;/renamepage&quot;;
        ///SET_INDEX = &quot;/setindex&quot;;
        ///SET_MAIN_INDEX = &quot;/setmainindex&quot;;
        ///RESET_INDEX = &quot;/resetindex&quot;;
        ///INSERT_PAGE = &quot;/insertpage&quot;;
        ///DELETE_PAGE = &quot;/deletepage&quot;;
        ///SWAP = &quot;/swap&quot;;
        ///TOGGLE = &quot;/toggle&quot;;
        ///
        ///DISPLAY_MANA_LIFE = &quot;/dml&quot;;
        ///DISPLAY_LIFE_MANA = &quot;/dlm&quot;;
        ///DISPLAY_LIFE = &quot;/dl&quot;; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ActiveCommands_Hint {
            get {
                return ResourceManager.GetString("ActiveCommands_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все файлы.
        /// </summary>
        public static string DlgFolderPlugyIni_AllFiles {
            get {
                return ResourceManager.GetString("DlgFolderPlugyIni_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все .ini.
        /// </summary>
        public static string DlgFolderPlugyIni_AllIni {
            get {
                return ResourceManager.GetString("DlgFolderPlugyIni_AllIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string LicenseMIT_Text {
            get {
                return ResourceManager.GetString("LicenseMIT_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PlugY.ini не найден.
        /// </summary>
        public static string PlugYiniNotFound_Heading {
            get {
                return ResourceManager.GetString("PlugYiniNotFound_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажете месторасположение PlugY.ini?.
        /// </summary>
        public static string PlugYiniNotFound_Question {
            get {
                return ResourceManager.GetString("PlugYiniNotFound_Question", resourceCulture);
            }
        }
    }
}
